### ISSUE TITLE
Uncaught SyntaxError: import not found: clamp

### ISSUE THREAD

**Issue by knightss27** [Ennoriel/svelte-awesome-color-picker#8]
Just decided to try this picker out as I appreciated the design, and ran into `Uncaught SyntaxError: import not found: clamp` immediately. You can recreate this by creating a brand new svelte/vite project and trying to load the picker.

Devtools links to the import from `chyme` in `Picker.svelte`.

**Comment by Ennoriel** [comment]
Ji there,

It did happen before but I fixed it. There is paybe something else happening.

I'll have an eye on this soon!

**Comment by Ennoriel** [comment]
Hey, I tried to install with `npm i -D svelte-awesome-color-picker` and copied the demo code in index.svelte without any trouble. Are you sure you installed the lastest version? I'll need a bit more insight to help you.

``` svelte
<script>
	import ColorPicker from 'svelte-awesome-color-picker';

	let rgb; // or hsv or hex
</script>

<ColorPicker bind:rgb />
```

**Comment by knightss27** [comment]
Yes still happening. I'm on the latest version of both svelte/vite and the color picker (1.2.3). Try this:

```
npm create vite@latest picker-test -- --template svelte
cd picker-test
npm install
npm i -D svelte-awesome-color-picker
# change the App.svelte page to what you said
npm run dev
```

For me in both Firefox and Chrome this throws the same `import not found` error.

**Comment by Ennoriel** [comment]
I didn't see your reply. 😨

I did try today the exact same thing and it's working like a charm.

- Are you working on windows?
- Do you see the lib `chyme` in your node_modules? If not, you can install it manually but you should definitely not have to
- Can you copy the full stacktrace?
